# SPDX-License-Identifier: GPL-2.0
# AnyRealm Kotoamatsukami Stealth Engine - NUKI/NURFS Unified
# Matrix: ANBU-style - each module stays itself, but under a team they merge

obj-y += Virtualspace.o
obj-y += hidden-objects.o
obj-y += kpm_eud_engine.o
obj-y += koto_core.o

obj-y += colonel/

obj-m += kpm_eud-hiddnobj-test.o
obj-m += kpm_eud-hiddnobj-emb.o
obj-m += kpm_eud-infusdobj-test.o
obj-m += kpm_eud-infusdobj-emb.o
obj-m += kpm_eud-outoftree-emb.o
obj-m += kpm_eud-upstrm-emb.o
