# SPDX-License-Identifier: GPL-2.0
# Colonel - Snapdragon Profile (SProf) - VFS Environment Shaping
# FLAGS = Logic | C/H Files = Movement | DISC = Proof | PATCH = Seal

obj-y += sprof_eud.o
obj-y += sprof_proc.o
obj-y += sprof_env.o
obj-y += sprof_profile.o
obj-y += sprof_vfs.o
obj-y += sprof_main.o

ccflags-y += -I$(src)
